function AboutPage() {
  return (
    <div className="min-h-screen flex flex-col mt-6 items-center">
      <section className="rounded px-8 pt-6 pb-8 mb-4 flex flex-col">
        <h1 className="mb-4 text-4xl font-bold text-white">
          About Patchwork Archive
        </h1>
        <section className="mb-2 text-xl text-white">
          <p className="leading-relaxed">
            Patchwork Archive aims to archive original songs and covers created
            by VTubers.
            <br />
            With loss of content being a major issue in VTubing (due to
            termination and graduations), the goal
            <br />
            of Patchwork Archive is to preserve a subset of VTuber content for
            preservation of culture.
            <br />
            <br />
            Original songs and covers are archived. Short form content that
            doesn&rsquo;t promote an existing music cover <br />
            or original song is archived. Streams, clips, etc. are not archived.
            <br />
            <br />
            All archived content was available publicly on YouTube at the time
            of processing.
          </p>
          <br />
          <p className="font-bold">
            Currently we archive the following data for each video:
          </p>
          <ul className="list-disc list-inside mt-4">
            <li className="mb-2">
              1080p version of each video <em>[lower if unavailable]</em>
            </li>
            <li className="mb-2">
              Highest available resolution thumbnail (maxresdefault.jpg){" "}
              <em>[lower if unavailable]</em>
            </li>
            <li className="mb-2">
              Metadata (in the form of .info.json generated by yt-dlp)
            </li>
            <li className="mb-2">
              All non-livechat and auto-generated captions in srv3
            </li>
          </ul>
        </section>
        <section className="mt-4 text-xl text-white">
          <h2 className="mt-4 mb-2 text-4xl font-bold text-white">
            How are videos sourced
          </h2>
          <p className="leading-relaxed">
            Simple answer is that they are scraped from YouTube and Holodex API,
            and then
            <br />
            manually processed to ensure that each video is a valid cover or
            original song.
            <br />
            <br />
            Some vidoes are missing metadata or captions as this data can no
            longer be retrieved.
          </p>
          <br />
            <p className="font-bold mb-3">
                Patchwork Archive is Open Source:
            </p>
        </section>
        <button className="px-4 py-2 font-bold text-white bg-black rounded-full hover:backdrop-brightness-50 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50">
          <a
            href="https://github.com/Patchwork-Archive"
            target="_blank"
            rel="noopener noreferrer"
          >
            View on GitHub
          </a>
        </button>
        <section className="mb-2 mt-4 text-xl text-white">
          <p className="leading-relaxed">
            Any legal inquiries can be directed to{" "}
            <a
              className="underline hover:underline-offset-4"
              href="mailto:pinapelz@moekyun.me"
            >
              pinapelz@moekyun.me
            </a>
          </p>
        </section>
        <p className="text-sm text-gray-400">API Documentation Coming Soon!!!</p>
      </section>
    </div>
  );
}

export default AboutPage;
